---

- name: Update GRUB - Add net.ifnames=0 to GRUB_CMDLINE_LINUX
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    backrefs: yes
    regexp: '^(GRUB_CMDLINE_LINUX=")(?!.*\bnet\.ifnames=0\b)(.*)(")$'
    line: '\g<1>\g<2> net.ifnames=0\g<3>'
    owner: root
    group: root
    mode: '0644'
  become: yes
  notify: Update GRUB


- ansible.builtin.set_fact: ifnames_file="/etc/udev/rules.d/70-custom-ifnames.rules"

- ansible.builtin.set_fact: ifnames_file_temp="{{ ifnames_file }}-temp"


- name: Ensure NetworkManager package is installed
  ansible.builtin.package:
    name: NetworkManager
    state: present
  become: yes
  register: nm_install_result

- name: Display NetworkManager installation status
  ansible.builtin.debug:
    msg: "NetworkManager has been successfully installed."
  when: nm_install_result.changed

- name: Display NetworkManager already present status
  ansible.builtin.debug:
    msg: "NetworkManager was already installed."
  when: not nm_install_result.changed

- name: Ensure a fresh, empty temporary udev rules file exists
  ansible.builtin.copy:
    dest: "{{ ifnames_file_temp }}"
    content: ""
    owner: root
    group: root
    mode: '0644'
    force: yes
  become: yes

- name: Create a sorted list of active, non-loopback interface names
  ansible.builtin.set_fact:
    network_adapters: "{{ ansible_facts.interfaces | reject('equalto', 'lo') | sort | list }}"

- name: Write persistent network interface rules to the temporary ifnames file
  ansible.builtin.lineinfile:
    path: "{{ ifnames_file_temp }}"
    line: 'SUBSYSTEM=="net", ACTION=="add", ATTR{address}=="{{ ansible_facts[item.1].macaddress }}", ATTR{type}=="1", NAME="eth{{ item.0 }}"'
  with_indexed_items: "{{ network_adapters }}"
  become: yes

- name: Replace the final udev rules file if it has changed
  ansible.builtin.copy:
    src: "{{ ifnames_file_temp }}"
    dest: "{{ ifnames_file }}"
    owner: root
    group: root
    mode: '0644'
    remote_src: yes
    backup: yes
  become: yes

- name: Clean up the temporary udev rules file
  ansible.builtin.file:
    path: "{{ ifnames_file_temp }}"
    state: absent
  become: yes

- name: Reboot the server to apply network changes
  ansible.builtin.reboot:
    pre_reboot_delay: 30
    post_reboot_delay: 30
    reboot_timeout: 100
  become: yes

